spring:
  application:
    name: covy-user

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
      # ??? create-drop: ?????? ??? ?, ??? ?? drop. ?????? ?? ?, ??? ?? ???.
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
#  datasource:
#    url: jdbc:mariadb://localhost:3306/mydb
#    driver-class-name: org.mariadb.jdbc.Driver
#    hikari:
#      username: root
#      password: test1357

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    server-url:
      defaultZone: http://127.0.0.1:8761/eureka


greeting:
  message: Welcome to the Simple E-commerce

logging:
  level:
    covy.covyuser.user: DEBUG


jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9==
  token_expiration_time: 86400000 # ttl (?)

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus