batch:
  jobs:
    goodsJob: "0 21 18 * * ?"

spring:
  application:
    name: covy-goods

#  Redis Default μ„Έν…
  data:
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris: localhost:9200

  batch:
    jdbc:
      initialize-schema: always

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: root
      password: test1357

  eureka:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      register-with-eureka: true
      fetch-registry: true
      server-url:
        defaultZone: http://127.0.0.1:8761/eureka

server:
  port: 0
